auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common_config:
  path_prefix: /tmp/loki
  storage_engine: "filesystem"
  chunk_target_size: 1048576

scrape_configs:
  - job_name: "promtail"
    static_configs:
      - targets:
          - "promtail:9080"
        labels:
          job: "promtail"
