version: 2.1

jobs:
  CI:
    machine: true # Use full VM with Docker pre-installed

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: |
            docker build -t pixelproxy:latest .

      - run:
          name: Run Docker Compose
          command: |
            docker-compose up -d --build

      - run:
          name: Install Trivy
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - run:
          name: Scan Image with Trivy
          command: |
            trivy image --exit-code 1 --ignore-unfixed --vuln-type os,library --format table pixelproxy:latest

      - run:
          name: Stop Docker Compose
          command: docker-compose down

      - run:
          name: Docker Login
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Tag & Push Docker Image
          command: |
            docker tag pixelproxy:latest $DOCKERHUB_USERNAME/pixelproxy:latest
            docker push $DOCKERHUB_USERNAME/pixelproxy:latest

workflows:
  build_and_push:
    jobs:
      - CI
