jobs:
  CI:
    machine: true

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: |
            docker build -t pixelproxy:latest .

      - run:
          name: Run Docker Compose
          command: |
            docker-compose up -d --build

      - run:
          name: Install Trivy
          command: |
            sudo apt-get update && sudo apt-get install -y wget rpm
            wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
            sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

      - run:
          name: Scan Image with Trivy
          command: |
            trivy image --exit-code 1 --ignore-unfixed --vuln-type os,library --format table pixelproxy:latest

      - run:
          name: Stop Docker Compose
          command: docker-compose down

      - run:
          name: Docker Login
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Tag & Push Docker Image
          command: |
            docker tag pixelproxy:latest $DOCKERHUB_USERNAME/pixelproxy:latest
            docker push $DOCKERHUB_USERNAME/pixelproxy:latest
